<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MarketsSeeder extends Seeder
{
    public function run(): void
    {
        $markets = [
            [
                'code' => 'es',
                'name' => 'España',
                'region' => 'EU_MDR',
                'default_language' => 'es',
                'enabled_languages' => json_encode(['es', 'en']),
                'active' => true,
                'priority' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'mx',
                'name' => 'México',
                'region' => 'LATAM_GENERIC',
                'default_language' => 'es',
                'enabled_languages' => json_encode(['es', 'en']),
                'active' => true,
                'priority' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'us',
                'name' => 'United States',
                'region' => 'FDA',
                'default_language' => 'en',
                'enabled_languages' => json_encode(['en', 'es']),
                'active' => true,
                'priority' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'fr',
                'name' => 'France',
                'region' => 'EU_MDR',
                'default_language' => 'fr',
                'enabled_languages' => json_encode(['fr', 'en']),
                'active' => false,
                'priority' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'it',
                'name' => 'Italy',
                'region' => 'EU_MDR',
                'default_language' => 'it',
                'enabled_languages' => json_encode(['it', 'en']),
                'active' => false,
                'priority' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'pt',
                'name' => 'Portugal',
                'region' => 'EU_MDR',
                'default_language' => 'pt',
                'enabled_languages' => json_encode(['pt', 'en']),
                'active' => false,
                'priority' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'de',
                'name' => 'Germany',
                'region' => 'EU_MDR',
                'default_language' => 'de',
                'enabled_languages' => json_encode(['de', 'en']),
                'active' => false,
                'priority' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ch',
                'name' => 'Switzerland',
                'region' => 'EU_MDR',
                'default_language' => 'de',
                'enabled_languages' => json_encode(['de', 'en']),
                'active' => false,
                'priority' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'at',
                'name' => 'Austria',
                'region' => 'EU_MDR',
                'default_language' => 'de',
                'enabled_languages' => json_encode(['de', 'en']),
                'active' => false,
                'priority' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'be',
                'name' => 'Belgium',
                'region' => 'EU_MDR',
                'default_language' => 'fr',
                'enabled_languages' => json_encode(['fr', 'en']),
                'active' => false,
                'priority' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'nl',
                'name' => 'Netherlands',
                'region' => 'EU_MDR',
                'default_language' => 'nl',
                'enabled_languages' => json_encode(['nl', 'en']),
                'active' => false,
                'priority' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'lu',
                'name' => 'Luxembourg',
                'region' => 'EU_MDR',
                'default_language' => 'fr',
                'enabled_languages' => json_encode(['fr', 'en']),
                'active' => false,
                'priority' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ie',
                'name' => 'Ireland',
                'region' => 'EU_MDR',
                'default_language' => 'en',
                'enabled_languages' => json_encode(['en', 'es']),
                'active' => false,
                'priority' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'gb',
                'name' => 'United Kingdom',
                'region' => 'UK_MDR',
                'default_language' => 'en',
                'enabled_languages' => json_encode(['en', 'es']),
                'active' => false,
                'priority' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'lt',
                'name' => 'Lithuania',
                'region' => 'EU_MDR',
                'default_language' => 'lt',
                'enabled_languages' => json_encode(['lt', 'en']),
                'active' => false,
                'priority' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'lv',
                'name' => 'Latvia',
                'region' => 'EU_MDR',
                'default_language' => 'lv',
                'enabled_languages' => json_encode(['lv', 'en']),
                'active' => false,
                'priority' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ee',
                'name' => 'Estonia',
                'region' => 'EU_MDR',
                'default_language' => 'ee',
                'enabled_languages' => json_encode(['ee', 'en']),
                'active' => false,
                'priority' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ar',
                'name' => 'Argentina',
                'region' => 'ANMAT',
                'default_language' => 'es',
                'enabled_languages' => json_encode(['es', 'en']),
                'active' => false,
                'priority' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'cl',
                'name' => 'Chile',
                'region' => 'ISP',
                'default_language' => 'es',
                'enabled_languages' => json_encode(['es', 'en']),
                'active' => false,
                'priority' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'co',
                'name' => 'Colombia',
                'region' => 'INVIMA',
                'default_language' => 'es',
                'enabled_languages' => json_encode(['es', 'en']),
                'active' => false,
                'priority' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'pe',
                'name' => 'Peru',
                'region' => 'DIGEMID',
                'default_language' => 'es',
                'enabled_languages' => json_encode(['es', 'en']),
                'active' => false,
                'priority' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ec',
                'name' => 'Ecuador',
                'region' => 'ARCSA',
                'default_language' => 'es',
                'enabled_languages' => json_encode(['es', 'en']),
                'active' => false,
                'priority' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'br',
                'name' => 'Brazil',
                'region' => 'ANVISA',
                'default_language' => 'pt',
                'enabled_languages' => json_encode(['pt', 'en']),
                'active' => false,
                'priority' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'sa',
                'name' => 'Saudi Arabia',
                'region' => 'SFDA',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ae',
                'name' => 'United Arab Emirates',
                'region' => 'MOHAP',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'qa',
                'name' => 'Qatar',
                'region' => 'MOPH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'kw',
                'name' => 'Kuwait',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'om',
                'name' => 'Oman',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'bh',
                'name' => 'Bahrain',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'jo',
                'name' => 'Jordan',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'lb',
                'name' => 'Lebanon',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'dz',
                'name' => 'Algeria',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'tn',
                'name' => 'Tunisia',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ma',
                'name' => 'Morocco',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ly',
                'name' => 'Libya',
                'region' => 'MOH',
                'default_language' => 'ar',
                'enabled_languages' => json_encode(['ar', 'en']),
                'active' => false,
                'priority' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'in',
                'name' => 'India',
                'region' => 'CDSCO',
                'default_language' => 'en',
                'enabled_languages' => json_encode(['en', 'hi']),
                'active' => false,
                'priority' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'cn',
                'name' => 'China',
                'region' => 'NMPA',
                'default_language' => 'zh',
                'enabled_languages' => json_encode(['zh', 'en']),
                'active' => false,
                'priority' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'jp',
                'name' => 'Japan',
                'region' => 'MHLW',
                'default_language' => 'ja',
                'enabled_languages' => json_encode(['ja', 'en']),
                'active' => false,
                'priority' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'kr',
                'name' => 'South Korea',
                'region' => 'MOH',
                'default_language' => 'ko',
                'enabled_languages' => json_encode(['ko', 'en']),
                'active' => false,
                'priority' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ru',
                'name' => 'Russia',
                'region' => 'MOH',
                'default_language' => 'ru',
                'enabled_languages' => json_encode(['ru', 'en']),
                'active' => false,
                'priority' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'tr',
                'name' => 'Turkey',
                'region' => 'MOH',
                'default_language' => 'tr',
                'enabled_languages' => json_encode(['tr', 'en']),
                'active' => false,
                'priority' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'ua',
                'name' => 'Ukraine',
                'region' => 'MOH',
                'default_language' => 'ua',
                'enabled_languages' => json_encode(['ua', 'en']),
                'active' => false,
                'priority' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'vn',
                'name' => 'Vietnam',
                'region' => 'MOH',
                'default_language' => 'vi',
                'enabled_languages' => json_encode(['vi', 'en']),
                'active' => false,
                'priority' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('markets')->insert($markets);
    }
}
