<template>
  <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-100">

    <div class="mb-6">
      <h3 class="text-lg font-semibold text-gray-900">Contenido Traducido</h3>
      <p class="mt-1 text-sm text-gray-500">
        Rellena el nombre y slug en cada idioma activo del sistema.
      </p>
    </div>

    <!-- Pestañas de idioma -->
    <!-- 
      Iteramos sobre props.languages que vienen del backend.
      Si se añade un nuevo idioma activo, aparece aquí automáticamente.
    -->
    <div class="flex flex-wrap gap-2 pb-4 mb-6 border-b border-gray-200">
      <button
        v-for="lang in languages"
        :key="lang.code"
        type="button"
        @click="activeLang = lang.code"
        :class="activeLang === lang.code
          ? 'bg-indigo-600 text-white shadow-sm'
          : 'bg-gray-100 text-gray-600 hover:bg-gray-200'"
        class="px-3 py-2 rounded-lg text-sm font-semibold transition-all flex items-center gap-2"
      >
        <span>{{ lang.name }}</span>
        <!-- Punto verde si este idioma tiene título relleno -->
        <span
          v-if="translations[lang.code]?.title?.trim()"
          class="w-2 h-2 rounded-full bg-green-400 flex-shrink-0"
          title="Tiene contenido"
        />
      </button>
    </div>

    <!-- Formulario del idioma activo -->
    <div v-if="activeLang && translations[activeLang]" class="space-y-6">

      <!-- Título -->
      <div>
        <label class="block text-sm font-medium text-gray-700">
          Nombre
          <span class="font-normal text-gray-400 text-xs ml-1">
            (en {{ currentLanguage?.name }})
          </span>
        </label>
        <input
          :value="translations[activeLang].title"
          @input="onTitleInput($event.target.value)"
          type="text"
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          :class="hasError(`translations.${activeLang}.title`)
            ? 'border-red-300 focus:border-red-500 focus:ring-red-500'
            : 'border-gray-300 focus:border-indigo-500 focus:ring-indigo-500'"
          :placeholder="`Nombre de la categoría en ${currentLanguage?.name}`"
        />
        <p v-if="hasError(`translations.${activeLang}.title`)" class="mt-1 text-sm text-red-600">
          {{ getError(`translations.${activeLang}.title`) }}
        </p>
      </div>

      <!-- Slug -->
      <div>
        <label class="block text-sm font-medium text-gray-700">Slug (URL)</label>
        <input
          :value="translations[activeLang].slug"
          @input="translations[activeLang].slug = $event.target.value"
          type="text"
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          placeholder="nombre-de-la-categoria"
        />
        <p class="mt-1 text-xs text-gray-400">
          Se genera automáticamente desde el nombre. Debe ser único.
        </p>
        <p v-if="hasError(`translations.${activeLang}.slug`)" class="mt-1 text-sm text-red-600">
          {{ getError(`translations.${activeLang}.slug`) }}
        </p>
      </div>

      <!-- Descripción -->
      <div>
        <label class="block text-sm font-medium text-gray-700">
          Descripción
          <span class="font-normal text-gray-400 text-xs ml-1">(opcional)</span>
        </label>
        <textarea
          :value="translations[activeLang].description"
          @input="translations[activeLang].description = $event.target.value"
          rows="3"
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          :placeholder="`Descripción en ${currentLanguage?.name}`"
        />
      </div>

    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import { slugify, isSlugAutoGenerated } from '@/utils/slug';
import { getFlagEmoji } from '@/utils/icons';

const props = defineProps({
  // Array de idiomas activos del sistema, viene del controlador:
  // [{ id: 1, code: "es", name: "Español" }, { id: 2, code: "en", name: "English" }]
  languages: {
    type: Array,
    required: true,
  },
  // v-model: objeto con claves por código de idioma
  // { "es": { language_id: 1, title: "", slug: "", description: "" }, ... }
  modelValue: {
    type: Object,
    required: true,
  },
  errors: {
    type: Object,
    default: () => ({}),
  },
});

const emit = defineEmits(['update:modelValue']);

// Idioma activo — empieza en el primero de la lista
const activeLang = ref(props.languages[0]?.code ?? 'es');

// Estado interno de traducciones.
// Construimos un objeto vacío por cada idioma activo,
// luego cargamos los datos existentes del modelValue (para edición).
const translations = ref(buildEmptyTranslations(props.languages));
Object.assign(translations.value, props.modelValue);

// Cada vez que cambia el estado interno, notificamos al padre
watch(translations, (newVal) => {
  emit('update:modelValue', newVal);
}, { deep: true, immediate: true });

// Idioma activo como objeto completo (para mostrar el nombre)
const currentLanguage = computed(() =>
  props.languages.find(l => l.code === activeLang.value) ?? null
);

// Historial de slugs generados automáticamente
// (para detectar si el admin lo editó manualmente)
const slugifiedTitles = ref({});

// Construye el objeto de traducciones vacío para todos los idiomas
function buildEmptyTranslations(languages) {
  const result = {};
  for (const lang of languages) {
    result[lang.code] = {
      language_id:  lang.id,
      title:        '',
      slug:         '',
      description:  '',
    };
  }
  return result;
}

// Cuando el admin escribe el título, actualiza el slug automáticamente
// pero solo si no lo ha editado manualmente
function onTitleInput(value) {
  translations.value[activeLang.value].title = value;

  const currentSlug  = translations.value[activeLang.value].slug ?? '';
  const expectedSlug = slugifiedTitles.value[activeLang.value] ?? '';

  if (isSlugAutoGenerated(currentSlug, expectedSlug)) {
    const newSlug = slugify(value);
    translations.value[activeLang.value].slug = newSlug;
    slugifiedTitles.value[activeLang.value] = newSlug;
  }
}

function hasError(field) {
  return !!props.errors[field];
}
function getError(field) {
  return props.errors[field] ?? '';
}
</script>