/**
 * Utilidades para generación de slugs.
 * 
 * Un slug es la versión URL-safe de un título:
 * "Novedades en Medicina" → "novedades-en-medicina"
 */

/**
 * Convierte un texto en un slug válido para URLs.
 * 
 * Pasos:
 * 1. Convierte a minúsculas
 * 2. Elimina acentos (é → e)
 * 3. Elimina caracteres especiales
 * 4. Reemplaza espacios por guiones
 * 
 * @param {string} text - Texto a slugificar
 * @returns {string} Slug resultante
 */
export function slugify(text) {
    if (!text) return "";
    
    return text
        .toLowerCase()
        .normalize("NFD") // Descompone "é" en "e" + acento combinado
        .replace(/[\u0300-\u036f]/g, "") // Elimina diacríticos
        .replace(/[^a-z0-9\s-]/g, "") // Solo letras, números, espacios, guiones
        .trim()
        .replace(/\s+/g, "-") // Espacios → guiones
        .replace(/-+/g, "-"); // Múltiples guiones → uno solo
}

/**
 * Detecta si un slug ha sido modificado manualmente por el usuario.
 * 
 * Compara el slug actual con lo que esperábamos que fuera generado
 * del título anterior. Si el usuario lo cambió a mano, no lo sobreescribimos.
 * 
 * @param {string} currentSlug - Slug actual en el formulario
 * @param {string} expectedSlug - Slug que esperábamos del título anterior
 * @returns {boolean} true si el slug NO ha sido modificado manualmente
 */
export function isSlugAutoGenerated(currentSlug, expectedSlug) {
    return currentSlug === "" || currentSlug === expectedSlug;
}
