/**
 * Composable: Localización Multi-Mercado e Idioma
 * 
 * USO BÁSICO:
 *   const { activeMarket, activeLanguage, localizations, ... } = useLocalizations(markets)
 * 
 * QUÉS ES:
 *   Encapsula toda la lógica para que un admin pueda crear contenido
 *   en múltiples mercados e idiomas simultáneamente (ej: artículos,
 *   productos, tratamientos, páginas).
 * 
 * EL PARÁMETRO `markets`:
 *   Array reactivo (ref o prop) con estructura del backend:
 *   [{ id, code, name, region, languages: [{ id, code, name, is_default }] }]
 * 
 * CAMPOS ADICIONALES:
 *   El segundo parámetro permite que módulos añadan campos propios:
 *   useLocalizations(markets, { indications: '', contraindications: '' })
 */

import { ref, computed } from "vue";
import { slugify, isSlugAutoGenerated } from "@/utils/slug";
import {
    buildLocalizationKey,
    buildAllLocalizations,
    loadExistingLocalizations as loadExistingLocalizationsUtil,
    getFilledLocalizations as getFilledLocalizationsUtil,
    hasLocalizationContent,
    hasMarketContent,
    countFilledLocalizations,
} from "@/utils/localizations";

export function useLocalizations(markets, extraFields = {}) {
    // SECCIÓN 1: ESTADO DE NAVEGACIÓN
    // El admin selecciona qué mercado e idioma quiere editar.
    // Se inicializa con el primer mercado y su idioma por defecto.

    const activeMarket = ref(
        markets.value?.[0]?.code ?? null
    );

    const activeLanguage = ref(
        getInitialLanguageCode(markets.value)
    );

    function getInitialLanguageCode(marketsArray) {
        const firstMarket = marketsArray?.[0];
        if (!firstMarket?.languages) return null;

        // Prefiere el idioma por defecto, si no, el primero disponible
        return (
            firstMarket.languages.find((l) => l.is_default)?.code ??
            firstMarket.languages[0]?.code ??
            null
        );
    }

    // SECCIÓN 2: ESTADO COMPUTADO
    // Buscamos en los markets los objetos completos correspondientes
    // a los códigos que el admin seleccionó.

    const currentMarket = computed(() =>
        markets.value?.find((m) => m.code === activeMarket.value) ?? null
    );

    const currentLanguage = computed(() =>
        currentMarket.value?.languages.find(
            (l) => l.code === activeLanguage.value
        ) ?? null
    );

    /**
     * Clave que identifica la localización activa: "es_es", "mx_en", etc.
     * Se usa como índice en el objeto de localizaciones.
     */
    const activeKey = computed(() =>
        buildLocalizationKey(activeMarket.value, activeLanguage.value)
    );

    // SECCIÓN 3: ESTADO DE DATOS
    // Las localizaciones: objeto con claves "es_es", "mx_en", etc.
    // Cada clave contiene { title, slug, excerpt, content, seo_metadata, ...extraFields }

    const localizations = ref(buildAllLocalizations(markets.value, extraFields));

    // Historial de slugs generados: para detectar si el admin los editó manualmente
    const slugifiedTitles = ref({});

    // SECCIÓN 4: ACCIONES DE NAVEGACIÓN

    /**
     * Cuando el admin cambia de mercado.
     * 
     * Al cambiar mercado, el idioma activo se resetea al idioma por
     * defecto del nuevo mercado. Esto evita quedar en un idioma que
     * no existe en el mercado nuevo.
     * 
     * Ejemplo:
     *   - Estás en "España > EN"
     *   - Cambias a "México"
     *   - Se activa automáticamente el idioma por defecto de México
     */
    function selectMarket(marketCode) {
        activeMarket.value = marketCode;
        const market = markets.value?.find((m) => m.code === marketCode);
        const defaultLang = market?.languages.find((l) => l.is_default);

        activeLanguage.value =
            defaultLang?.code ?? market?.languages[0]?.code ?? null;
    }

    // SECCIÓN 5: GENERACIÓN AUTOMÁTICA DE SLUG
    // Cuando el admin escribe el título, el slug se genera automáticamente.
    // "Novedades en Medicina Estética 2025" → "novedades-en-medicina-estetica-2025"

    /**
     * Maneja el evento de cambio en el título.
     * 
     * Genera el slug automáticamente, PERO solo si el admin no lo ha
     * editado manualmente. Detectamos esto comparando el slug actual
     * con el slug que esperábamos del título anterior.
     */
    function onTitleInput(key) {
        const title = localizations.value[key]?.title ?? "";
        const currentSlug = localizations.value[key]?.slug ?? "";
        const previousExpectedSlug = slugifiedTitles.value[key] ?? "";

        // Si el slug está vacío o coincide con lo que generamos antes,
        // lo actualizamos. Si el admin lo cambió a mano, lo dejamos.
        if (isSlugAutoGenerated(currentSlug, previousExpectedSlug)) {
            const newSlug = slugify(title);
            localizations.value[key].slug = newSlug;
            slugifiedTitles.value[key] = newSlug;
        }
    }

    // SECCIÓN 6: HELPERS PARA VIS UAL DE ESTADO
    // El componente las usa para mostrar indicadores visuales.

    /**
     * ¿Tiene contenido (título) la combinación mercado + idioma?
     */
    function hasContent(marketCode, langCode) {
        return hasLocalizationContent(localizations.value, marketCode, langCode);
    }

    /**
     * ¿Tiene algún idioma con contenido en este mercado?
     */
    function marketHasContent(marketCode) {
        return hasMarketContent(localizations.value, markets.value, marketCode);
    }

    /**
     * Cuántas localizaciones están completadas.
     * Usado para mostrar en el sidebar: "3/8 completadas"
     */
    const filledCount = computed(() =>
        countFilledLocalizations(localizations.value)
    );

    // SECCIÓN 7: DATOS PARA ENVIAR AL BACKEND

    /**
     * Retorna solo las localizaciones que tienen contenido.
     * 
     * Las vacías se filtran. No tiene sentido crear filas en la BD
     * con todo en blanco.
     */
    function getFilledLocalizations() {
        return getFilledLocalizationsUtil(localizations.value);
    }

    // SECCIÓN 8: CARGA DE DATOS EXISTENTES (para edición)

    /**
     * Carga localizaciones que ya están guardadas.
     * 
     * Usado cuando el formulario es de EDICIÓN (no creación).
     * El backend envía los datos existentes, esta función los carga.
     * 
     * @param {Array} existing - Las localizaciones guardadas del backend
     */
    function loadExistingLocalizations(existing) {
        loadExistingLocalizationsUtil(existing, markets.value, localizations.value);

        // También inicializamos el historial de slugs
        // para que no se sobreescriban al editar
        for (const loc of existing ?? []) {
            const market = markets.value?.find((m) => m.id === loc.market_id);
            const lang = market?.languages.find((l) => l.id === loc.language_id);
            if (market && lang) {
                const key = buildLocalizationKey(market.code, lang.code);
                slugifiedTitles.value[key] = slugify(loc.title ?? "");
            }
        }
    }

    // SECCIÓN 9: RETORNO (API PÚBLICA DEL COMPOSABLE)

    return {
        // Estado de navegación
        activeMarket,
        activeLanguage,
        activeKey,
        currentMarket,
        currentLanguage,

        // Los datos
        localizations,

        // Acciones
        selectMarket,
        onTitleInput,
        loadExistingLocalizations,
        getFilledLocalizations,

        // Helpers visuales
        hasContent,
        marketHasContent,
        filledCount,

        // Utilidad pública (usada por componentes)
        slugify,
    };
}
